name: Testing

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set gfortran link on macos-latest
      if: matrix.os == 'macos-latest'
      run: |
        set -x
        sudo ln -s /usr/local/bin/gfortran-11 /usr/local/bin/gfortran
        gfortran --version

    - name: Install dependencies via pip
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Unit tests
      run: |
        pip install camb
        python -m unittest sptpol_2017.tests.test_sptpol
        python -m unittest spt_hiell_2020.tests.test_spt_hiell
        python -m unittest spt3g_2020.tests.test_spt3g
        python -m unittest spt3g_2022.tests.test_spt3g
